### ISSUE TITLE
local: bindle fails to start on Linux

### ISSUE THREAD

**Issue by bacongobbler** [fermyon/installer#58]
After https://github.com/fermyon/installer/pull/41, bindle will no longer start. Here's the logs from the failed allocation:

```
/home/bacongobbler/code/installer/local/data/nomad/alloc/3170e2a5-5fbb-ee12-fa8d-879d892d6f79/bindle/local/bindle-server: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

I have `libssl-dev` installed locally.

Removing the `artifact` from the job fixes the issue because I have a compiled version of bindle using my system's openssl libs.

**Comment by lann** [comment]
Is this on Ubuntu 22.04 perchance?

**Comment by lann** [comment]
OK, so presumably the same issue as https://github.com/fermyon/spin/issues/498

**Comment by lann** [comment]
We solved the above by statically linking openssl in `spin`. We could do the same for `bindle-server` but would either need to update that in bindle's CI or ship a separate release for the demo.

**Comment by vdice** [comment]
Closed by https://github.com/fermyon/installer/pull/59
