### ISSUE TITLE
Add Azure installer

### ISSUE THREAD

**Issue by radu-matei** [fermyon/installer#62]
This repository contains instructions and configuration for deploying Fermyon locally and on AWS.
It would be great to have Terraform configuration for deploying to Azure.

**Comment by bnookala** [comment]
@radu-matei I would like to take this on!

**Comment by scotty-c** [comment]
If you need help with this one we can help as well

**Comment by jldeen** [comment]
Hi all, I just opened a PR for Azure install support via Terraform. Feedback / constructive criticism welcome!

**Comment by vdice** [comment]
Added in https://github.com/fermyon/installer/pull/81 🎉
