### ISSUE TITLE
Add Digital Ocean installer

### ISSUE THREAD

**Issue by radu-matei** [fermyon/installer#71]
This repository contains instructions and configuration for deploying Fermyon locally and on AWS.
It would be great to have Terraform configuration for deploying to Digital Ocean.

ref https://www.digitalocean.com/community/tutorials/how-to-use-terraform-with-digitalocean

**Comment by FrankYang0529** [comment]
I can help to add Digital Ocean installer after https://github.com/fermyon/installer/pull/76 is merged. May I assign this to myself?

**Comment by vdice** [comment]
> May I assign this to myself?

Definitely!  I've taken the liberty to do so.  Thank you!
