### ISSUE TITLE
Bump spin version in cloud installers

### ISSUE THREAD

**Issue by vdice** [fermyon/installer#83]
Bump the `spin` version to the latest release ([v0.4.0](https://github.com/fermyon/spin/releases/tag/v0.4.0) at time of writing) in the remote/cloud installer scenarios.  Be sure to test the [app deployment flow](https://github.com/fermyon/installer/blob/main/deploy.md) with the latest version.

Currently, we just have this spot in the AWS installer: https://github.com/fermyon/installer/blob/main/aws/terraform/main.tf#L21

But we are soon to add GCP and Azure; in particular, the spin version (along with other dependencies) will most likely be tracked in a shared file, ref https://github.com/fermyon/installer/pull/76

**Comment by acald-creator** [comment]
Hi there, I like to try my hand at this.

**Comment by vdice** [comment]
Thank you @acald-creator! I've assigned you to the issue.

**Comment by radu-matei** [comment]
Awesome, @acald-creator, let us know if we can help with anything!

**Comment by vdice** [comment]
PS @acald-creator, note that Spin [v0.4.0](https://github.com/fermyon/spin/releases/tag/v0.4.0) has just been released today.  We probably want to bump to this version.  (I'll edit the description above.)

**Comment by acald-creator** [comment]
Thanks for the update. I just changed it to the `v0.4.0` version. So far, it deployed correctly in AWS, trying for `local` now.

**Comment by vdice** [comment]
Closed by https://github.com/fermyon/installer/issues/83 🎉
